# Codecov configuration to make it a bit less noisy
coverage:
  ignore:
    -QUBEKit/test/.*
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null