[build-system]
requires = ["setuptools >= 61.0", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "qubekit"
description = "Quantum mechanical bespoke force field parameter generation."
authors = [
  {name = "Joshua Thomas Horton", email = "Josh.Horton@newcastle.ac.uk"},
  {name = "Chris Ringrose"},
  {name = "Daniel Cole"}
]
maintainers = [
   {name = "Joshua Thomas Horton", email = "Josh.Horton@newcastle.ac.uk"}
]
readme = "README.md"
requires-python = ">= 3.10"
license = {file = "LICENSE.txt"}

[project.scripts]
qubekit = "qubekit.cli.cli:cli"

[project.urls]
Repository = "https://github.com/qubekit/QUBEKit"

[project.entry-points."openff.toolkit.plugins.handlers"]
QUBEKitvdWTS = "qubekit.cli.utils:QUBEKitHandler"
LocalCoordinateVirtualSites = "qubekit.cli.utils:LocalCoordinateVirtualSiteHandler"
UreyBradley = "qubekit.cli.utils:UreyBradleyHandler"
ProperRyckhaertBellemans = "qubekit.cli.utils:ProperRyckhaertBellemansHandler"
BondChargeCorrection = "qubekit.cli.utils:BondChargeCorrectionHandler"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "qubekit/_version.py"
versionfile_build = "qubekit/_version.py"
tag_prefix = ""
parentdir_prefix = "qubekit-"

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

target-version = "py310"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"


[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "qubekit.__version__"}

[tool.setuptools.packages.find]
namespaces = true
where = ["."]
