package:
  name: qubekit
  version: 2.3.4

source:
  path: ../..

build:
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - networkx
    - matplotlib
    - scipy

about:
  home: https://github.com/qubekit/QUBEKit
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Quantum mechanical bespoke force field derivation toolkit
  doc_url: https://github.com/qubekit/QUBEKit

extra:
  recipe-maintainers:
    - CRingrose94
